repos:
-   repo: local
    hooks:
    -   id: autoflake
        name: autoflake
        entry: uv run autoflake
        args: [-i, -r, --remove-all-unused-imports, --remove-unused-variables]
        language: system
        types: [python]
        pass_filenames: true
        files: '^(src|tests)/'


    -   id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [file, python]
        files: '^(src|tests)/'

    -   id: black
        name: black
        entry: uv run black
        language: system
        types: [file, python]
        files: '^(src|tests)/'

    -   id: tox
        name: tox
        entry: uv run tox
        language: system
        types: [file, python]
        pass_filenames: false
        always_run: true

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []